image: Ubuntu1804 # образ для сборки
stack: node 12 # окружение
branches:
  only:
    - main # ветка git
cache: node_modules # кеширование
install:
  - npm install # команда для установки зависимостей
build: off
test_script:
  - npm run lint && npm test # скрипт сборки